version: '3'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - caddy_net

  adminportal:
    image: repasscloud/optechx-portaladmin:latest
    container_name: optechx-portaladmin
    networks:
      - caddy_net

networks:
  caddy_net:

volumes:
  caddy_data: